-- Define la variable para la ruta base
SET @base_path = '/API/paticas-api/external-resources/optimized-images-for-testing/';


INSERT INTO pet (profile_image, image_carousel1, image_carousel2, image_carousel3, name, location, gender, size, birth_date, species, description, good_with_kids, good_with_dogs, good_with_cats, shelter_id) VALUES 
(CONCAT(@base_path,'profile_1.jpg'), CONCAT(@base_path,'carousel1_1.jpg'), CONCAT(@base_path,'carousel2_1.jpg'), CONCAT(@base_path,'carousel3_1.jpg'), 'Max', 'Murcia', 'male', 2, '2018-05-15', 'Perro', 'Max es un perro cariñoso y juguetón. Siempre ansioso por paseos y haciendo nuevos amigos', true, false, true, 10),
(CONCAT(@base_path,'profile_2.jpg'), CONCAT(@base_path,'carousel1_2.jpg'), CONCAT(@base_path,'carousel2_2.jpg'), CONCAT(@base_path,'carousel3_2.jpg'), 'Luna', 'Murcia', 'female', 3, '2019-07-20', 'Gato', 'Luna es una gatita tranquila y afectuosa, exploradora y juguetona. Su curiosidad la lleva a descubrir cada rincón.', false, true, true, 10),
(CONCAT(@base_path,'profile_3.jpg'), CONCAT(@base_path,'carousel1_3.jpg'), CONCAT(@base_path,'carousel2_3.jpg'), CONCAT(@base_path,'carousel3_3.jpg'), 'Charlie', 'Murcia', 'male', 1, '2017-10-10', 'Perro', 'Charlie es un perrito adorable y juguetón, amante del aire libre y las siestas. Su energía es contagiosa y su ternura, irresistible.', true, true, true, 10),
(CONCAT(@base_path,'profile_4.jpg'), CONCAT(@base_path,'carousel1_4.jpg'), CONCAT(@base_path,'carousel2_4.jpg'), CONCAT(@base_path,'carousel3_4.jpg'), 'Bella', 'Murcia', 'female', 2, '2019-02-28', 'Gato', 'Bella es una gatita elegante y cariñosa, adora mimarse y explorar. Su gracia y curiosidad la hacen única.', true, true, false, 10),
(CONCAT(@base_path,'profile_5.jpg'), CONCAT(@base_path,'carousel1_5.jpg'), CONCAT(@base_path,'carousel2_5.jpg'), CONCAT(@base_path,'carousel3_5.jpg'), 'Rocky', 'Murcia', 'male', 3, '2016-08-05', 'Perro', 'Rocky es un perro valiente y leal, listo para explorar y jugar. Su amor por la vida es inspirador.', false, true, true, 10),
(CONCAT(@base_path,'profile_6.jpg'), CONCAT(@base_path,'carousel1_6.jpg'), CONCAT(@base_path,'carousel2_6.jpg'), CONCAT(@base_path,'carousel3_6.jpg'), 'Milo', 'Murcia', 'male', 1, '2020-04-12', 'Perro', 'Milo es un cachorro dulce y juguetón, ansioso por explorar y jugar. Siempre lleno de alegría y energía.', true, true, true, 10),
(CONCAT(@base_path,'profile_7.jpg'), CONCAT(@base_path,'carousel1_7.jpg'), CONCAT(@base_path,'carousel2_7.jpg'), CONCAT(@base_path,'carousel3_7.jpg'), 'Chloe', 'Murcia', 'female', 2, '2019-11-18', 'Gato', 'Chloe es una gatita curiosa y cariñosa, feliz explorando y acariciada. Su amor es contagioso y su curiosidad, infinita.', true, true, true, 10),
(CONCAT(@base_path,'profile_8.jpg'), CONCAT(@base_path,'carousel1_8.jpg'), CONCAT(@base_path,'carousel2_8.jpg'), CONCAT(@base_path,'carousel3_8.jpg'), 'Oscar', 'Murcia', 'male', 3, '2018-09-25', 'Perro', 'Oscar es un perro amigable y activo, disfruta caminatas y amigos. Siempre lleno de energía y entusiasmo.', true, true, false, 10), 
(CONCAT(@base_path,'profile_9.jpg'), CONCAT(@base_path,'carousel1_9.jpg'), CONCAT(@base_path,'carousel2_9.jpg'), CONCAT(@base_path,'carousel3_9.jpg'), 'Lucy', 'Murcia', 'female', 2, '2020-01-30', 'Gato', 'Lucy es una gata cariñosa y tranquila, disfruta siestas y mimos. Su calma y dulzura son reconfortantes.', true, true, true, 10), 
(CONCAT(@base_path,'profile_10.jpg'), CONCAT(@base_path,'carousel1_10.jpg'), CONCAT(@base_path,'carousel2_10.jpg'), CONCAT(@base_path,'carousel3_10.jpg'), 'Leo', 'Murcia', 'male', 1, '2019-03-10', 'Perro', 'Leo es un cachorro lleno de energía y entusiasmo, siempre curioso. Siempre dispuesto a descubrir algo nuevo.', true, true, true, 10), 
(CONCAT(@base_path,'profile_11.jpg'), CONCAT(@base_path,'carousel1_11.jpg'), CONCAT(@base_path,'carousel2_11.jpg'), CONCAT(@base_path,'carousel3_11.jpg'), 'Coco', 'Murcia', 'female', 2, '2018-12-12', 'Gato', 'Coco es una gatita traviesa y cariñosa, amante de la aventura. Su espíritu juguetón la hace encantadora.', true, true, true, 10), 
(CONCAT(@base_path,'profile_12.jpg'), CONCAT(@base_path,'carousel1_12.jpg'), CONCAT(@base_path,'carousel2_12.jpg'), CONCAT(@base_path,'carousel3_12.jpg'), 'Buddy', 'Murcia', 'male', 3 , '2017-08-20', 'Perro', 'Buddy es un perro cariñoso y protector, ideal para compañía fiel. Siempre listo para cuidar a su familia.', true, true, true, 10),
(CONCAT(@base_path,'profile_13.jpg'), CONCAT(@base_path,'carousel1_13.jpg'), CONCAT(@base_path,'carousel2_13.jpg'), CONCAT(@base_path,'carousel3_13.jpg'), 'Mia', 'Murcia', 'female', 1, '2020-10-05', 'Perro', 'Mia es una cachorra dulce y juguetona, llena de alegría. Su vitalidad y cariño son contagiosos.', true, true, true, 10), 
(CONCAT(@base_path,'profile_14.jpg'), CONCAT(@base_path,'carousel1_14.jpg'), CONCAT(@base_path,'carousel2_14.jpg'), CONCAT(@base_path,'carousel3_14.jpg'), 'Simba', 'Murcia', 'male', 2, '2019-04-15', 'Gato', 'Simba es un gato valiente y curioso, disfruta trepando. Siempre explorando su reino con confianza.', true, true, true, 10),
(CONCAT(@base_path,'profile_15.jpg'), CONCAT(@base_path,'carousel1_15.jpg'), CONCAT(@base_path,'carousel2_15.jpg'), CONCAT(@base_path,'carousel3_15.jpg'), 'Daisy', 'Murcia', 'female', 3, '2018-02-28', 'Perro', 'Daisy es una perrita enérgica y juguetona, perfecta para aventuras. Siempre lista para correr y jugar.', true, true, true, 10), 
(CONCAT(@base_path,'profile_16.jpg'), CONCAT(@base_path,'carousel1_16.jpg'), CONCAT(@base_path,'carousel2_16.jpg'), CONCAT(@base_path,'carousel3_16.jpg'), 'Oreo', 'Murcia', 'male', 1, '2020-07-10', 'Gato', 'Oreo es un gato cariñoso y juguetón, siempre explorando. Siempre descubriendo nuevos rincones.', true, true, true, 10), 
(CONCAT(@base_path,'profile_17.jpg'), CONCAT(@base_path,'carousel1_17.jpg'), CONCAT(@base_path,'carousel2_17.jpg'), CONCAT(@base_path,'carousel3_17.jpg'), 'Paquito', 'Murcia', 'male', 3, '2017-08-20', 'Perro', 'Paquito es un perro cariñoso y protector, leal y activo. Siempre dispuesto a proteger a sus seres queridos.', true, true, true, 10),
(CONCAT(@base_path,'profile_18.jpg'), CONCAT(@base_path,'carousel1_18.jpg'), CONCAT(@base_path,'carousel2_18.jpg'), CONCAT(@base_path,'carousel3_18.jpg'), 'Star', 'Murcia', 'female', 2, '2019-12-10', 'Perro', 'Star es una perrita cariñosa y juguetona, llena de ternura. Siempre lista para brindar amor y diversión.', true, true, true, 10), 
(CONCAT(@base_path,'profile_19.jpg'), CONCAT(@base_path,'carousel1_19.jpg'), CONCAT(@base_path,'carousel2_19.jpg'), CONCAT(@base_path,'carousel3_19.jpg'), 'Sam', 'Murcia', 'male', 1, '2020-03-20', 'Gato', 'Sam es un gatito curioso y travieso, lleno de vida. Siempre buscando nuevas travesuras y aventuras.', true, true, true, 10), 
(CONCAT(@base_path,'profile_20.jpg'), CONCAT(@base_path,'carousel1_20.jpg'), CONCAT(@base_path,'carousel2_20.jpg'), CONCAT(@base_path,'carousel3_20.jpg'), 'Dean', 'Murcia', 'male', 3, '2018-08-15', 'Perro', 'Dean es un perro que se atreve con todo lo que la vida le presente. Le encanta explorar el aire libre y jugar con pelotas y juguetes.', false, true, true, 10);



INSERT INTO volunteer (profile_image, full_name, phone, email, availability, shelter_id) VALUES 
(CONCAT(@base_path,'profile_image_1.jpg'), 'Juan Pérez', '623456789', 'juan@example.com', 1, 10),
(CONCAT(@base_path,'profile_image_2.jpg'), 'María López', '687654321', 'maria@example.com', 2, 10),
(CONCAT(@base_path,'profile_image_3.jpg'), 'Pedro García', '656789123', 'pedro@example.com', 3, 10),
(CONCAT(@base_path,'profile_image_4.jpg'), 'Ana Martínez', '654321987', 'ana@example.com', 1, 10),
(CONCAT(@base_path,'profile_image_5.jpg'), 'David Rodríguez', '621654987', 'david@example.com', 2, 10),
(CONCAT(@base_path,'profile_image_6.jpg'), 'Laura Ruiz', '689123456', 'laura@example.com', 3, 10),
(CONCAT(@base_path,'profile_image_7.jpg'), 'Carlos Sánchez', '634567891', 'carlos@example.com', 1, 10),
(CONCAT(@base_path,'profile_image_8.jpg'), 'Sofía García', '676543219', 'sofia@example.com', 2, 10),
(CONCAT(@base_path,'profile_image_9.jpg'), 'Pablo Díaz', '667891234', 'pablo@example.com', 3, 10);
