-- Define la variable para la ruta base
SET @base_path = 'API/paticas-api/external-resources/optimized-images-for-testing/';

INSERT INTO shelter (id, profileImage, name, location, description) VALUES 
(10, CONCAT(@base_path,'shelter_profile_image.jpg'), 'Refugio de Paticas', 'Murcia', 'Nuestro refugio se dedica a proporcionar un hogar seguro y amoroso para animales necesitados. Trabajamos arduamente para garantizar que cada mascota reciba la atención y el cuidado que merece. Ven a visitarnos y encuentra a tu nuevo amigo peludo.');


INSERT INTO pet (profileImage, imageCarousel1, imageCarousel2, imageCarousel3, name, location, gender, size, birthDate, species, description, goodWithKids, goodWithDogs, goodWithCats) VALUES 
(CONCAT(@base_path,'profile_1.jpg'), CONCAT(@base_path,'carousel1_1.jpg'), CONCAT(@base_path,'carousel2_1.jpg'), CONCAT(@base_path,'carousel3_1.jpg'), 'Max', 'Murcia', 'male', 2, '2018-05-15', 'Perro', 'Max es un perro cariñoso y juguetón que disfruta de largos paseos por el parque. Tiene una personalidad extrovertida y le encanta conocer a nuevos amigos, tanto humanos como peludos. Su pelaje suave y brillante lo hace destacar entre la multitud, y su lealtad hacia su familia lo convierte en el compañero perfecto para cualquier hogar. Si estás buscando un compañero lleno de energía y amor, ¡Max es la elección ideal!', true, false, true),
(CONCAT(@base_path,'profile_2.jpg'), CONCAT(@base_path,'carousel1_2.jpg'), CONCAT(@base_path,'carousel2_2.jpg'), CONCAT(@base_path,'carousel3_2.jpg'), 'Luna', 'Murcia', 'female', 3, '2019-07-20', 'Gato', 'Luna es una gatita tranquila y afectuosa que disfruta pasar el tiempo acurrucada en el regazo de sus seres queridos. Le encanta explorar su entorno y descubrir nuevos rincones para descansar. Su pelaje suave y sus ojos curiosos hacen que sea irresistible para cualquiera que la conozca. A pesar de su naturaleza reservada, Luna está lista para adaptarse a un nuevo hogar donde pueda brindar amor y compañía sin medida. ¡Haz espacio en tu vida para esta dulce gatita!', false, true, true),
(CONCAT(@base_path,'profile_3.jpg'), CONCAT(@base_path,'carousel1_3.jpg'), CONCAT(@base_path,'carousel2_3.jpg'), CONCAT(@base_path,'carousel3_3.jpg'), 'Charlie', 'Murcia', 'male', 1, '2017-10-10', 'Perro', 'Charlie es un perrito adorable y juguetón que está buscando un hogar lleno de amor y diversión. Le encanta correr y jugar al aire libre, pero también disfruta de largas siestas acurrucado en una manta suave. Su naturaleza amigable lo hace perfecto para familias con niños y otros animales. Si quieres agregar alegría y compañía a tu vida, ¡Charlie es la elección perfecta!', true, true, true),
(CONCAT(@base_path,'profile_4.jpg'), CONCAT(@base_path,'carousel1_4.jpg'), CONCAT(@base_path,'carousel2_4.jpg'), CONCAT(@base_path,'carousel3_4.jpg'), 'Bella', 'Murcia', 'female', 2, '2019-02-28', 'Gato', 'Bella es una gatita elegante y cariñosa que adora ser mimada y consentida. Le gusta pasar las tardes tomando largas siestas al sol y las noches explorando su hogar con curiosidad. Su pelaje suave y su mirada tierna la convierten en una compañera irresistible. Si estás buscando a alguien para compartir momentos de tranquilidad y amor, ¡Bella es la compañera perfecta!', true, true, false),
(CONCAT(@base_path,'profile_5.jpg'), CONCAT(@base_path,'carousel1_5.jpg'), CONCAT(@base_path,'carousel2_5.jpg'), CONCAT(@base_path,'carousel3_5.jpg'), 'Rocky', 'Murcia', 'male', 3, '2016-08-05', 'Perro', 'Rocky es un perro valiente y leal que está listo para cualquier aventura que la vida le presente. Le encanta explorar el aire libre y jugar con pelotas y juguetes. Su energía contagiosa y su amor incondicional hacen que sea el compañero ideal para personas activas y enérgicas. Si buscas un compañero fiel y lleno de vida, ¡Rocky es la elección perfecta!', false, true, true),
(CONCAT(@base_path,'profile_6.jpg'), CONCAT(@base_path,'carousel1_6.jpg'), CONCAT(@base_path,'carousel2_6.jpg'), CONCAT(@base_path,'carousel3_6.jpg'), 'Milo', 'Murcia', 'male', 1, '2020-04-12', 'Perro', 'Milo es un cachorro dulce y juguetón que está ansioso por explorar el mundo que lo rodea. Le encanta jugar con juguetes y correr por el jardín. Su ternura y su naturaleza juguetona lo hacen irresistible para cualquiera que lo conozca. Si buscas un amigo peludo para compartir risas y aventuras, ¡Milo es el compañero perfecto!', true, true, true),
(CONCAT(@base_path,'profile_7.jpg'), CONCAT(@base_path,'carousel1_7.jpg'), CONCAT(@base_path,'carousel2_7.jpg'), CONCAT(@base_path,'carousel3_7.jpg'), 'Chloe', 'Murcia', 'female', 2, '2019-11-18', 'Gato', 'Chloe es una gatita curiosa y cariñosa que disfruta pasar el tiempo explorando su entorno y descubriendo nuevos lugares para esconderse y jugar. Le encanta recibir caricias y ronronea felizmente cuando está rodeada de afecto. Su personalidad encantadora la convierte en la compañera perfecta para cualquier hogar. Si buscas a alguien para llenar tu vida de alegría y amor, ¡Chloe es la gatita para ti!', true, true, true),
(CONCAT(@base_path,'profile_8.jpg'), CONCAT(@base_path,'carousel1_8.jpg'), CONCAT(@base_path,'carousel2_8.jpg'), CONCAT(@base_path,'carousel3_8.jpg'), 'Oscar', 'Murcia', 'male', 3, '2018-09-25', 'Perro', 'Oscar es un perro amigable y activo que disfruta de largas caminatas y juegos al aire libre. Le encanta socializar con otros perros y personas, y siempre está listo para hacer nuevos amigos. Su energía contagiosa y su naturaleza afectuosa lo convierten en el compañero ideal para familias activas y enérgicas. Si buscas un amigo peludo para compartir aventuras y momentos especiales, ¡Oscar es el perro para ti!', true, true, false), 
(CONCAT(@base_path,'profile_9.jpg'), CONCAT(@base_path,'carousel1_9.jpg'), CONCAT(@base_path,'carousel2_9.jpg'), CONCAT(@base_path,'carousel3_9.jpg'), 'Lucy', 'Murcia', 'female', 2, '2020-01-30', 'Gato', 'Lucy es una gata cariñosa y tranquila que disfruta de largas siestas al sol y de mimos suaves. Le encanta estar cerca de sus seres queridos y pasar tiempo acurrucada en el regazo. Su dulce personalidad y su mirada tierna la convierten en una compañera perfecta para cualquier hogar. Si buscas a alguien para compartir', true, true, true), 
(CONCAT(@base_path,'profile_10.jpg'), CONCAT(@base_path,'carousel1_10.jpg'), CONCAT(@base_path,'carousel2_10.jpg'), CONCAT(@base_path,'carousel3_10.jpg'), 'Leo', 'Murcia', 'male', 1, '2019-03-10', 'Perro', 'Leo es un cachorro lleno de energía y entusiasmo que está listo para explorar el mundo que lo rodea. Le encanta jugar al aire libre y correr por el parque. Su curiosidad y su amor por la vida lo convierten en el compañero perfecto para aventuras emocionantes. Si buscas un amigo leal y juguetón, ¡Leo es el cachorro para ti!', true, true, true), 
(CONCAT(@base_path,'profile_11.jpg'), CONCAT(@base_path,'carousel1_11.jpg'), CONCAT(@base_path,'carousel2_11.jpg'), CONCAT(@base_path,'carousel3_11.jpg'), 'Coco', 'Murcia', 'female', 2, '2018-12-12', 'Gato', 'Coco es una gatita traviesa y cariñosa que adora explorar su entorno y jugar con juguetes coloridos. Le encanta trepar a lugares altos y observar el mundo desde arriba. Su naturaleza juguetona y su amor por la aventura la convierten en una compañera emocionante para cualquier hogar. Si buscas una gatita llena de vida y diversión, ¡Coco es la elección perfecta!', true, true, true), 
(CONCAT(@base_path,'profile_12.jpg'), CONCAT(@base_path,'carousel1_12.jpg'), CONCAT(@base_path,'carousel2_12.jpg'), CONCAT(@base_path,'carousel3_12.jpg'), 'Buddy', 'Murcia', 'male', 3 , '2017-08-20', 'Perro', 'Buddy es un perro cariñoso y protector que está siempre listo para cuidar de su familia. Le encanta pasar tiempo al aire libre y correr por el campo. Su lealtad y devoción hacen que sea el compañero ideal para aquellos que buscan un amigo fiel. Si quieres tener a un compañero leal y afectuoso a tu lado, ¡Buddy es el perro para ti!', true, true, true),
(CONCAT(@base_path,'profile_13.jpg'), CONCAT(@base_path,'carousel1_13.jpg'), CONCAT(@base_path,'carousel2_13.jpg'), CONCAT(@base_path,'carousel3_13.jpg'), 'Mia', 'Murcia', 'female', 1, '2020-10-05', 'Perro', 'Mia es una cachorra dulce y juguetona que adora pasar tiempo con su familia. Le encanta explorar el jardín y jugar con sus juguetes favoritos. Su ternura y su alegría contagiosa iluminan cualquier hogar. Si buscas un compañero fiel y lleno de vida, ¡Mia es la elección perfecta!', true, true, true), 
(CONCAT(@base_path,'profile_14.jpg'), CONCAT(@base_path,'carousel1_14.jpg'), CONCAT(@base_path,'carousel2_14.jpg'), CONCAT(@base_path,'carousel3_14.jpg'), 'Simba', 'Murcia', 'male', 2, '2019-04-15', 'Gato', 'Simba es un gato valiente y curioso que está listo para conquistar el mundo. Le encanta trepar a lugares altos y observar su reino desde lo alto. Su pelaje suave y su mirada confiada lo hacen destacar entre la multitud. Si buscas un compañero majestuoso y lleno de carácter, ¡Simba es el rey de tu corazón!', true, true, true), 
(CONCAT(@base_path,'profile_15.jpg'), CONCAT(@base_path,'carousel1_15.jpg'), CONCAT(@base_path,'carousel2_15.jpg'), CONCAT(@base_path,'carousel3_15.jpg'), 'Daisy', 'Murcia', 'female', 3, '2018-02-28', 'Perro', 'Daisy es una perrita enérgica y juguetona que está siempre lista para la diversión. Le encanta correr por el parque y jugar con otros perros. Su amor por la vida y su espíritu alegre la convierten en la compañera perfecta para aventuras emocionantes. Si buscas un amigo peludo para compartir risas y momentos especiales, ¡Daisy es la compañera para ti!', true, true, true), 
(CONCAT(@base_path,'profile_16.jpg'), CONCAT(@base_path,'carousel1_16.jpg'), CONCAT(@base_path,'carousel2_16.jpg'), CONCAT(@base_path,'carousel3_16.jpg'), 'Oreo', 'Murcia', 'male', 1, '2020-07-10', 'Gato', 'Oreo es un gato cariñoso y juguetón que adora pasar tiempo con su familia. Le encanta jugar con sus juguetes favoritos y explorar su entorno con curiosidad. Su pelaje suave y su mirada tierna lo convierten en la compañía perfecta para largas tardes de mimos y caricias. Si buscas un amigo felino para llenar tu vida de alegría, ¡Oreo es la elección ideal!', true, true, true), 
(CONCAT(@base_path,'profile_17.jpg'), CONCAT(@base_path,'carousel1_17.jpg'), CONCAT(@base_path,'carousel2_17.jpg'), CONCAT(@base_path,'carousel3_17.jpg'), 'Buddy', 'Murcia', 'male', 3, '2017-08-20', 'Perro', 'Buddy es un perro cariñoso y protector que está siempre listo para cuidar de su familia. Le encanta pasar tiempo al aire libre y correr por el campo. Su lealtad y devoción hacen que sea el compañero ideal para aquellos que buscan un amigo fiel. Si quieres tener a un compañero leal y afectuoso a tu lado, ¡Buddy es el perro para ti!', true, true, true),
(CONCAT(@base_path,'profile_18.jpg'), CONCAT(@base_path,'carousel1_18.jpg'), CONCAT(@base_path,'carousel2_18.jpg'), CONCAT(@base_path,'carousel3_18.jpg'), 'Luna', 'Murcia', 'female', 2, '2019-12-10', 'Perro', 'Luna es una perrita cariñosa y juguetona que adora pasar tiempo con su familia. Le encanta explorar el jardín y jugar con sus juguetes favoritos. Su ternura y su alegría contagiosa iluminan cualquier hogar. Si buscas un compañero fiel y lleno de vida, ¡Luna es la elección perfecta!', true, true, true), 
(CONCAT(@base_path,'profile_19.jpg'), CONCAT(@base_path,'carousel1_19.jpg'), CONCAT(@base_path,'carousel2_19.jpg'), CONCAT(@base_path,'carousel3_19.jpg'), 'Milo', 'Murcia', 'male', 1, '2020-03-20', 'Gato', 'Milo es un gatito curioso y travieso que adora explorar su entorno y jugar con juguetes coloridos. Le encanta trepar a lugares altos y observar el mundo desde arriba. Su naturaleza juguetona y su amor por la aventura lo convierten en la compañía perfecta para cualquier hogar. Si buscas un compañero lleno de vida y diversión, ¡Milo es la elección ideal!', true, true, true), 
(CONCAT(@base_path,'profile_20.jpg'), CONCAT(@base_path,'carousel1_20.jpg'), CONCAT(@base_path,'carousel2_20.jpg'), CONCAT(@base_path,'carousel3_20.jpg'), 'Rocky', 'Murcia', 'male', 3, '2018-08-15', 'Perro', 'Rocky es un perro valiente y leal que está listo para cualquier aventura que la vida le presente. Le encanta explorar el aire libre y jugar con pelotas y juguetes. Su energía contagiosa y su amor incondicional hacen que sea el compañero ideal para personas activas y enérgicas. Si buscas un compañero fiel y lleno de vida, ¡Rocky es la elección perfecta!', false, true, true);



INSERT INTO volunteer (profileImage, fullName, phone, email, availability, shelter_id) VALUES 
(CONCAT(@base_path,'profile_image_1.jpg'), 'Juan Pérez', '623456789', 'juan@example.com', 1, 10),
(CONCAT(@base_path,'profile_image_2.jpg'), 'María López', '687654321', 'maria@example.com', 2, 10),
(CONCAT(@base_path,'profile_image_3.jpg'), 'Pedro García', '656789123', 'pedro@example.com', 3, 10),
(CONCAT(@base_path,'profile_image_4.jpg'), 'Ana Martínez', '654321987', 'ana@example.com', 1, 10),
(CONCAT(@base_path,'profile_image_5.jpg'), 'David Rodríguez', '621654987', 'david@example.com', 2, 10),
(CONCAT(@base_path,'profile_image_6.jpg'), 'Laura Ruiz', '689123456', 'laura@example.com', 3, 10),
(CONCAT(@base_path,'profile_image_7.jpg'), 'Carlos Sánchez', '634567891', 'carlos@example.com', 1, 10),
(CONCAT(@base_path,'profile_image_8.jpg'), 'Sofía García', '676543219', 'sofia@example.com', 2, 10),
(CONCAT(@base_path,'profile_image_9.jpg'), 'Pablo Díaz', '667891234', 'pablo@example.com', 3, 10);
